### ISSUE TITLE
MapToApiVersion on a controller action prevents other actions from executing

### ISSUE THREAD

**Issue by overdunne** [dotnet/aspnet-api-versioning#884] opened 2022-10-03 13:02 UTC
If I have an action [HttpGet("{id}")], and [MapToApiVersion("1.5")], then that method will be invoked instead of another method with a different route.

For the controller below, if I invoke http://localhost:5167/v1.5/Message/Test, then the Id method instead is run.  If I remove the MapToApiVersion attribute, then it behaves as expected.

```c#
[Route("v{version:apiVersion}/[controller]")]
[ApiController]
[ApiVersion("1.5")]
[ApiVersion("1.6")]
public class MessageController
{
    [HttpGet("Test")]
    public string Get()
    {
        return "Test";
    }

    [HttpGet("{id}")]
    [MapToApiVersion("1.5")]
    public string Id(string id)
    {
        return "You asked for: " + id;
    }
}
```

**Comment by commonsensesoftware** [comment] 2022-10-03 16:20
Confirmed; this is a bug. The issue is that _explicit_ version matches are considered over _implicit_ versions (match or map) without considering the _score_ of the match. The `Id` route overlaps with `Get`, but `Get` has a lower _score_ (e.g. it's a better match). `Get` isn't being resolved because it is an _implicit_ version match (e.g. no explicit mapping).

This will be fixed in `6.1` which should be this week. You can work around the issue by explicitly mapping versions to `Get`. 

```c#
[HttpGet("Test")]
[MapToApiVersion("1.5")]
[MapToApiVersion("1.6")]
public string Get() => "Test";
```

**Closed** 2022-10-03 21:19 UTC
Labels: bug, asp.net core
