### ISSUE TITLE
Fallback to last version when using ASP.NET Core date versioning

### ISSUE THREAD

**Issue by bogdan-filip** [dotnet/aspnet-api-versioning#762] opened 2021-07-28 20:37 UTC
Hi. I'm trying to version my API using dates and I want to receive from the client let's say the current day and fallback to the most recent version of the API.

Example:
Service X having 2 versions of API:
**2020-01-01**
**2021-01-01**

If client calls with version newer than **2021-01-01** - then provide newest API (**2021-01-01**)
If client calls with version between **2020-01-01** and **2021-01-01** - then provide older API (**2020-01-01**)

How can I achieve this? Right now whenever I receive a date that's not defined as a version I get the **UnsupportedApiVersion** error.

Thanks!

**Comment by commonsensesoftware** [comment] 2021-07-28 21:18
API versions **must** be discrete - by design. Achieving ranges is possible, but not supported out of the box as there is no universal way to define _increments_. The [Extensions and Customizations](../wiki/Extensions-and-Customizations) wiki topic outlines some possible options. There are also some older issues that discuss possible ways of achieving ranges.

The **IApiVersionSelector** can technically do this job, but it doesn't come into play if the client explicitly specifies an API version; again - by design. Another challenge is that there isn't a guaranteed way to know upfront the collated set of API versions to choose from until the route candidates have been identified. API Versioning has no way to know or guarantee that your versions are symmetrical across all APIs.

If your APIs do have symmetrical versions, then you can use the world's simplest middleware that does something like:

```c#
var feature = httpContext.Features.Get<IApiVersioningFeature>();

if (feature.RequestedApiVersion is ApiVersion version && (version >= minVersion && version < maxVersion))
{
    feature.RequestedApiVersion = targetVersion;
}
```

>:bulb: Although this is possible, you should use extreme caution in doing so unless you own both sides (e.g. client and server). A server **cannot** make _any_ assumptions about what a client can handle. Even additive changes _can_ break a client. An API version is really more like a media type as it almost always relates to payload format and should be treated as such. If a client requests an unsupported media type, the server cannot make assumptions, which is why 406 and 415 exist. It's true that a client doesn't _have_ to specify a media type (browsers often do that), in which case understanding the response is on them. Generic interfaces, such as browsers, can render the body as plain text, but that typically won't work for APIs. This can also confuse clients as they may not know which API they are bound to. Unless a client is _grandfathered_ in for backward compatibility, they _should_ always explicitly ask for a specific API version.

**Comment by bogdan-filip** [comment] 2021-07-29 06:33
Thank you for you quick response!

**Comment by bogdan-filip** [comment] 2021-07-29 08:11
Thanks again. I've manage to make it work. This is the code for the middleware.
```
public class ApiVersioningMiddleware
{
    private readonly RequestDelegate _next;
    private readonly IApiVersionDescriptionProvider _provider;

    public ApiVersioningMiddleware(
        RequestDelegate next,
        IApiVersionDescriptionProvider provider)
    {
        _next = next;
        _provider = provider;
    }

    public async Task Invoke(HttpContext context)
    {
        if (context is null)
        {
            throw new ArgumentNullException(nameof(context));
        }

        var apiVersions = _provider.ApiVersionDescriptions.OrderByDescending(x => x.ApiVersion);

        var feature = context.Features.Get<IApiVersioningFeature>();

        if (feature.RequestedApiVersion is ApiVersion apiVersion)
        {
            var version = apiVersions.FirstOrDefault(x => x.ApiVersion <= apiVersion);

            if (version == null)
            {
                version = apiVersions.FirstOrDefault();
            }

            feature.RequestedApiVersion = version.ApiVersion;
        }

        await _next(context);
    }
}
```

**Comment by commonsensesoftware** [comment] 2021-07-29 15:20
That's a neat idea. I didn't consider that ... if you're also using the API Explorer extensions.  With this approach **and** symmetrical versions, you _could_ use the **IApiVersionSelector**.

```c#
public class ApiVersioningMiddleware
{
    private readonly RequestDelegate _next;
    private readonly IApiVersionSelector _selector;
    private readonly IApiVersionDescriptionProvider _provider;
    private ApiVersionModel _model;

    public ApiVersioningMiddleware(
        RequestDelegate next,
        IApiVersionSelector selector
        IApiVersionDescriptionProvider provider)
    {
        _next = next;
        _selector = selector;
        _provider = provider;
    }

    private ApiModel ApplicationModel
    {
        get
        {
            if (_model is not null)
            {
                return _model;
            }

            var supported = new List<ApiVersion>();
            var deprecated = new List<ApiVersion>();

            for (var i = 0; i < _provider.ApiVersionDescriptions.Count; i++)
            {
                var description = _provider.ApiVersionDescriptions[i];

                if (description.IsDeprecated)
                {
                    deprecated.Add(description.ApiVersion);
                }
                else
                {
                    supported.Add(description.ApiVersion);
                }
           }

           // since the results are idempotent, this is thread-safe
           return _model = new ApiVersionModel(supported, deprecated);
        }
    }

    public async Task Invoke(HttpContext context)
    {
        if (context is null)
        {
            throw new ArgumentNullException(nameof(context));
        }

        var feature = context.Features.Get<IApiVersioningFeature>();
        feature.RequestedApiVersion = _selector.SelectVersion(context.Request, ApplicationModel);
        await _next(context);
    }
}

public class FallbackApiVersionSelector : IApiVersionSelector
{
    // note: this method must NOT return null
    public ApiVersion SelectVersion(HttpRequest request, ApiVersionModel model)
    {
        var version = request.HttpContext.GetRequestedApiVersion();

        if (version is null)
        {
            // TODO: chose an alternate fallback
            return ApiVersion.Neutral;
        }

        var versions = model.ImplementedVersions;
        var fallback = versions.LastOrDefault(v => v <= version) ?? versions.FirstOrDefault();

        // TODO: chose an alternate fallback
        fallback ??= ApiVersion.Neutral;

        return fallback;
    }
}
```

You would then this configure your selector in the options like so:

```c#
services.AddApiVersioning(options => options.ApiVersionSelector = new FallbackApiVersionSelector());
```

The advantage of this approach is that it is easier to reuse or change over time. The result is the same. If you don't plan to reuse this approach, then it probably doesn't matter. Just a suggestion. Glad you got things working.

**Comment by commonsensesoftware** [comment] 2022-03-20 22:39
I'm in the process of burning down issues. As this question has been answered and has a solution, I'm closing it out. Thanks.

**Closed by commonsensesoftware** 2022-03-20 22:39 UTC
Labels: question, answered, asp.net core
