### ISSUE TITLE
Issue with complex object as Action param with odata versioning

### ISSUE THREAD

**Issue by pashokchakravarthi** [dotnet/aspnet-api-versioning#708] opened 2020-12-07 17:17 UTC
We are using **Microsoft.AspNetCore.OData (v7.4.0)** with AspNet Core Rest API's. The endpoints enabled with OData has _**Complex type object as parameter**_ - which is working fine.
Now we are trying to add api versioning support to our api's, using the latest Microsoft.AspNetCore.OData.Versioning package v5.0.0.0 - Facing issue described below. When complex type object param is removed, everything seems to be working fine.

Able to recreate the issue with sample project **AdvancedODataSample**  available in this repo.
![image](https://user-images.githubusercontent.com/15814359/101373812-65140d80-38d3-11eb-8095-2395a5b59dd3.png)

Issue:
![image](https://user-images.githubusercontent.com/15814359/101382305-cd67ec80-38dd-11eb-8b98-91c979e22f77.png)

**Comment by commonsensesoftware** [comment] 2021-06-24 07:03
Sorry for the long overdue follow up to this question. I'm pretty sure that this is actually the same problem as in #711. I'll have to dig in deeper, but it seems that optional and complex query parameters are not matched. There's probably some update to the OData routing from the code I had to fork that is resulting in a miss. Hopefully, the solution will address both problems.

**Comment by commonsensesoftware** [comment] 2022-08-24 01:48
Last call. Did you ever find a solution? Are you still using OData 7.x? API Versioning `6.0` has been released with support for OData 8.x. The OData team fixed many of the routing issues and API Versioning doesn't need to get nearly as involved with duplicating or changes things like it used to. If you're stuck on OData 7.x, then I need to reprioritize this work for a patch release.

**Comment by commonsensesoftware** [comment] 2022-09-29 02:18
I'm sure this was probably an issue at some point. Based on the way routing works in OData `7.x`, it's quite likely a 🐞 in the `5.x` flavor of API Versioning. I can confirm that this is a non-issue with API Versioning `6.0`+ and OData `8.x`+.

I made the same changes you made in the advanced OData example with this request:

`https://localhost:5001/api/orders/1?api-version=2.0&tstModel.Id=42&tstModel.Name=Test`

And the result is:

![image](https://user-images.githubusercontent.com/11765008/192923484-8329cfcb-1b89-4635-90bb-46fc3cdb907e.png)

Model binding is working as expected.

Since this thread has also gone idle, I'm going to close it out. If you happen to see something resurface in `6.0`+, I'm happy to investigate or reopen the issue. Thanks.

**Closed by commonsensesoftware** 2022-09-29 02:18 UTC
Labels: answered, asp.net core, odata
